name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Create NPM Config
        run: |
          echo "@mykoboard:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PAT_TOKEN }}" >> .npmrc

      - name: Install Dependencies
        run: bun install --no-frozen-lockfile

      - name: Build
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          commit_message: "Deploy from ${GITHUB_SHA}"
